name: Code Formatting

on: [push]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --write "src/**/*.{js,vue,scss,html,md,json}" --ignore-path .gitignore

      - name: Commit formatted files
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-format code"
          git push